apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "guardian-forms"
  name: "guardian-forms"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "guardian-forms"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "guardian-forms"
    spec:
      containers:
        - image: andrewrisse/guardian-forms
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /manifest.json
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /manifest.json
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          name: "guardian-forms"
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
